name: Build, pack and release project

on: [push, pull_request]
  
jobs:
  build_pack_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: |
        chmod +x /home/runner/work/ContosoPets.Api/ContosoPets.Api/build.sh
        /home/runner/work/ContosoPets.Api/ContosoPets.Api/build.sh --target=CI --API-Key=${{env.NUGET_GPR_KEY}}
      env:
        NUGET_GPR_KEY: ${{secrets.NUGET_GPR}}
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ContosoPets.Api
        path: /home/runner/work/ContosoPets.Api/ContosoPets.Api/dist/ContosoPets.Api.*.nupkg
    - name: Release artifact to github nuget
      run: dotnet nuget push "./dist/ContosoPets.Api.*.nupkg" -s "https://nuget.pkg.github.com/Roy19/index.json" -k ${{env.NUGET_GPR_KEY}} --skip-duplicate
    


