name: Build, pack and release project

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: chmod 777 /home/runner/work/ContosoPets.Api/ContosoPets.Api/build.sh && /home/runner/work/ContosoPets.Api/ContosoPets.Api/build.sh
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ContosoPets.Api
        path: /home/runner/work/ContosoPets.Api/ContosoPets.Api/dist/ContosoPets.Api.*.nupkg
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Release artifact to github nuget
      run: /home/runner/work/ContosoPets.Api/ContosoPets.Api/build.sh -t Release -API-Key ${{ secrets.GITHUB_TOKEN }}
      shell: bash


